version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./allure-report:/allure-report
    environment:
      - ALLURE_HOME=/opt/allure

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:4040"
    volumes:
      - ./allure-report:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=60
      - KEEP_HISTORY=true
    depends_on:
      - jenkins

volumes:
  jenkins_data: